In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("insurance_data.csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2,random_state=18)

In [4]:
len(X_train)

22

**Preprocessing: Scale the data so that both age and affordibility are in same scaling range**

X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

**Model Building: First build a model in keras/tensorflow and see what weights and bias values it comes up with. We will then try to reproduce same weights and bias in our plain python implementation of gradient descent.**

In [8]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=2100)

Epoch 1/2100


C:\Users\Abhay\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 319ms/step - accuracy: 0.5909 - loss: 0.6766
Epoch 2/2100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5909 - loss: 0.6763
Epoch 3/2100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5909 - loss: 0.6760
Epoch 4/2100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5909 - loss: 0.6757
Epoch 5/2100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5909 - loss: 0.6754
Epoch 6/2100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5909 - loss: 0.6751
Epoch 7/2100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5909 - loss: 0.6748
Epoch 8/2100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5909 - loss: 0.6745
Epoch 9/2100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5909 - loss: 0.6742
Epoch 10/2100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5909 - loss: 0.6739
Epoch 11/2100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5909 - loss: 0.6736
Epoch 12/2100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5909 - lo

**Evaluate the model on test set**

In [9]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.8333 - loss: 0.5898


[0.5897970795631409, 0.8333333134651184]

In [10]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step


array([[0.4102768 ],
       [0.4955828 ],
       [0.77273554],
       [0.41800025],
       [0.63653105],
       [0.40259743]], dtype=float32)

**Now get the value of weights and bias from the model**

In [11]:
coef, intercept = model.get_weights()

In [12]:
coef, intercept

(array([[3.183312  ],
        [0.47248426]], dtype=float32),
 array([-1.1904823], dtype=float32))

**This means w1=5.060867, w2=1.4086502, bias =-2.9137027**