In [25]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [26]:
reviews = ['nice food',
           'amazing restaurant',
           'too good',
           'just makes my mouth water!!',
           'will go again',
           'bad service',
           'hated the experience',
           'very poor',
           'needs improvement',
           'very bad customer service']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [27]:
one_hot("amazing restaurant",30)

[16, 29]

In [28]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[21, 8],
 [16, 29],
 [4, 11],
 [29, 28, 28, 10, 18],
 [25, 14, 8],
 [1, 16],
 [9, 14, 12],
 [12, 24],
 [19, 28],
 [12, 1, 4, 16]]

In [29]:
# For padding
max_length = 5
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[21,  8,  0,  0,  0],
       [16, 29,  0,  0,  0],
       [ 4, 11,  0,  0,  0],
       [29, 28, 28, 10, 18],
       [25, 14,  8,  0,  0],
       [ 1, 16,  0,  0,  0],
       [ 9, 14, 12,  0,  0],
       [12, 24,  0,  0,  0],
       [19, 28,  0,  0,  0],
       [12,  1,  4, 16,  0]], dtype=int32)

In [30]:
embedded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length=max_length, name="embeddings"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [31]:
X = padded_reviews
y = sentiment

In [34]:
model.build(input_shape=(None, max_length))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embeddings (Embedding)          │ (None, 5, 5)           │           150 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 25)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            26 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 176 (704.00 B)

 Trainable params: 176 (704.00 B)

 Non-trainable params: 0 (0.00 B)

In [35]:
model.fit(X,y,epochs=50,verbose=0)

In [36]:
model.evaluate(X,y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - accuracy: 0.9000 - loss: 0.6268


[0.6267781257629395, 0.8999999761581421]

In [39]:
weights = model.get_layer('embeddings').get_weights()[0]

In [40]:
weights[0]

array([ 0.00230614, -0.02574511,  0.02006552,  0.0387512 , -0.01474966],
      dtype=float32)

In [41]:
weights[1]

array([-0.03586522, -0.08284546, -0.0703603 , -0.00965063,  0.11077842],
      dtype=float32)